### ISSUE TITLE
Request: shows previous answered questions

### ISSUE THREAD

**Issue by jrandhawa09** [neeilan/flowchart#1]
Hi 

Came across this plugin and really like it. Is it possible for you to update to include option to show the previous cards (questions) rather than hiding the parent (similar example at http://www.guiideas.com/2013/09/interactive-decision-guide.html but that uses tables).

I tried commenting out the following lines

//parent.removeClass(animateIn).addClass(animateOut);
//parent.hide();

which sort of works, but there is an issue when I click a different button to a previous question, the "old" answers remains visible. I'd like to refresh the nodes after the button selection.

Thanks

Jas

**Comment by neeilan** [comment]
#

**Comment by neeilan** [comment]
Hi Jas,
Glad you found the plugin helpful. The newest commit takes care of this issue - simply set the `preserveParentCards`parameter to true while initializing. 

For example:
`$("body").fc("bounceIn","fadeOut",1000, true);
`

Note that back button functionality is disabled (and probably not needed) when the parent cards aren't hidden. Also, the CSS issues have been fixed (you don't manually need to update your stylesheet before use anymore). 

Neeilan

# c4166e6e3c273270f67ac85825a7c15ad92bde73

**Comment by jrandhawa09** [comment]
Hi 

Works a treat. Thanks for the quick repsonse.

Jas
